# Generated by Django 4.2 on 2023-04-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_follow_author_alter_follow_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
